### PR TITLE
fix: all account details

### LINKED ISSUE #3417: Stabilize useDataLoader component
### Description of problem
Account info and device count isn't being updated instantaneously after changing it in "All account details" or "My devices"

### Expected behaviour
Account info and device count should be updated instantaneously after changing it in "All account details" or "My devices"

### Steps to reproduce
Log in as a verified account, navigate to Account tab, remove one of your devices under "My devices (n)" and verify n doesn't change after removing a device. Same approach for changing your email using "All account details"

### Screenshots and/or log output
N/A

### Environment
All

Build #: 5089

Android Device Model:
Any

iOS Device Model:
Any

### Workaround
Restart app or sign out and in again

### PR DESCRIPTION
**Pull request by al-rosenthal**
# Summary of Changes

- surfaced refresh function from account context
- added refresh on screen load to `Account.tsx`

# Testing Instructions

- Setup and verify same account on 2 different devices
- on device A, navigate to account screen
- open my devices
- remove device b
- go back to account screen
- see my devices count go down*

*There is currently a bug with the device count being off by 1

# Acceptance Criteria

Replace this text with the acceptance criteria that must be met for this PR to be approved.

# Screenshots, videos, or gifs

n/a

# Related Issues

[BC-Wallet: 3417](https://github.com/bcgov/bc-wallet-mobile/issues/3417)

### CODE REVIEW

File: app/src/bcsc-theme/features/account/Account.tsx [hunk 1]
```diff
@@ -47,28 +48,33 @@ const Account: React.FC = () => {
     loadBcscServiceClient()
   }, [loadBcscServiceClient])
 
+  const refreshData = useCallback(() => {
+    refreshAccount()
+    refreshIdToken()
```
Comment (bryce-mcmath) [inline app/src/bcsc-theme/features/account/Account.tsx:52]: Does refreshIdToken cause a new refresh token to be fetched every time?

Comment (al-rosenthal) [reply app/src/bcsc-theme/features/account/Account.tsx:52]: Correct, the token has the device count information on it, so if any devices are removed we need to update that as well

File: app/src/bcsc-theme/contexts/BCSCAccountContext.tsx [hunk 2]
```diff
@@ -96,3 +99,16 @@ export const useAccount = () => {
...
+ */
+export const useRefreshAccount = () => {
+  const context = useContext(BCSCAccountContext)
+
+  if (!context) {
+    throw new Error('useRefreshAccount must be used within a BCSCAccountProvider')
+  }
+
+  return context.refreshAccount
+}
```
Comment (MacDeluca) [inline app/src/bcsc-theme/contexts/BCSCAccountContext.tsx]: suggestion: I think we should probably just return the context from the `useAccount` hook.

```ts
const { account, refreshAccount, isLoadingAccount } = useAccount()
```

**Review by bryce-mcmath — APPROVED** [review]
